package tests;
// Generated by CodiumAI

import org.junit.Test;
import week1.CheckedExceptionExample;
import week1.CustomException;

import static org.junit.Assert.*;

public class CheckfilexistsTest {


    // Given a valid file path, the method should not throw an exception.
    @Test
    public void test_valid_file_path() {
        try {
            CheckedExceptionExample.checkFileExists("valid.txt");
        } catch (CustomException e) {
            fail("Unexpected exception thrown");
        }
    }

    // Given a null file path, the method should throw a CustomException.
    @Test
    public void test_null_file_path() {
        assertThrows(CustomException.class, () -> {
            CheckedExceptionExample.checkFileExists(null);
        });
    }

    // Given an empty file path, the method should throw a CustomException.
    @Test
    public void test_empty_file_path() {
        assertThrows(CustomException.class, () -> {
            CheckedExceptionExample.checkFileExists("");
        });
    }

}